inherits = 'blight'

# ====================== COLORS ======================

[palette]
foreground = '#4f4c4a'
foreground-subtle = '#b5b2b0'
foreground-elusive = '#ceccca'

background = '#ede4de'
background-subtle = '#e4d6cd'

red = '#bd7575'
yellow = '#bdab75'
green = '#75bd75'

red-subtle = '#dbbdbd'
yellow-subtle = '#dbd4bd'
green-subtle = '#bddbbd'

accent-1 = '#bd9275'
accent-2 = '#8f75bd'
accent-3 = '#bd75b8'
accent-4 = '#75a5bd'

accent-1-subtle = '#dbc9bd'
accent-2-subtle = '#c8bddb'
accent-3-subtle = '#dbbdd9'
accent-4-subtle = '#bdd1db'
